GET http://localhost:5114/games

###
GET http://localhost:5114/games/d9260447-ca66-45bf-80e6-79c59c329001
###
GET http://localhost:5114/generes
###
POST http://localhost:5114/games
Content-Type: application/json

{
    "name":"",
    "genereId":"",
    "price":19.99,
    "releaseDate":"2011-11-18",
    "description":""
}

###
PUT http://localhost:5114/games/6bad81cc-2143-4484-b2bd-9ce807d0a80e
Content-Type: application/json

{
    "name": "Street Fighter II Turbo",
    "genere": "Fighting",
    "price": 9.99,
    "releaseDate": "1992-07-15"
}

###
DELETE http://localhost:5114/games/6ede27c6-eeca-47ed-a313-2ca3fdbb6ecf