GET http://localhost:5114/games

###
GET http://localhost:5114/games/047c0695-9bae-4342-9a68-a36735d4f73c
###
GET http://localhost:5114/generes
###
POST http://localhost:5114/games
Content-Type: application/json

{
    "name": "TEST Game 2",
    "genereId":"B8936AFA-3526-4E19-84AA-71951806AA06",
    
    "price": 19.99,
    "releaseDate": "1992-07-15",
    "description":"Survive the night"
}

###
PUT http://localhost:5114/games/3ECAC533-8B0D-4F64-9CC2-A89FC4C13D64
Content-Type: application/json

{
    "name": "Minecraft",
    "genereId":"5A4E861F-05D7-41AC-A092-69F8F459C612",
    
    "price": 19.99,
    "releaseDate": "1992-07-15",
    "description":"Survive the day"
}

###
DELETE http://localhost:5114/games/3126FF52-7A21-4DF1-8EE9-5E81F3FE1F0B