GET http://localhost:5114/games

###
GET http://localhost:5114/games/23012e52-81e5-4037-8d21-5ff9d86d891f
###
GET http://localhost:5114/generes
###
POST http://localhost:5114/games
Content-Type: application/json

{
    "name": "Minecraft",
    "genereId":"cbb77890-c040-4e1b-84ee-c7e3cf534898",
    
    "price": 9.99,
    "releaseDate": "1992-07-15",
    "description":"Survive the night"
}

###
PUT http://localhost:5114/games
Content-Type: application/json

{
    "name": "Minecraft",
    "genreId":"eb0d3649-e0cc-4b7b-802c-5b5e7a6ec61e",
    
    "price": 9.99,
    "releaseDate": "1992-07-15",
    "description":"Survive the night"
}

###
DELETE http://localhost:5114/games/23012e52-81e5-4037-8d21-5ff9d86d891f